### ISSUE TITLE
facial landmarks

### ISSUE THREAD

**Issue by glmanhtu** [dkollias/Aff-Wild-models#7]
Hello Dimitrios,

From what I understand in the paper, the model would take both face image and its 2D landmarks as input for training the network, could you please let me know, how did you train your model on both image and 2D landmarks ? did you inject it somewhere in the FC layer or concatenate with the image ?

Thanks,

**Comment by dkollias** [comment]
Hello Vũ Mạnh Tú,

The landmarks were fed as input to the (first) fully connected layer along with: (i) the outputs of the ResNet-50, or (ii) the outputs of the last pooling layer of the VGG-Face/VGG-16. So in other words, the landmarks were concatenated with the outputs of ResNet-50/last pooling layer of the VGG-Face/VGG-16 and then fed as input to the fully connected layer of the developed architecture. Hope this clarifies things!

**Comment by glmanhtu** [comment]
Hello Dimitrios,

Thank you for clarifying, it really helpful.
I have one more question, in the paper you said that the images were cropped to 224 x 224 or 96 x 96. So, which resolution were being used in the pretrained model ? I also curious about which one gave you the better result ?

**Comment by dkollias** [comment]
All trained models (that we release here) need as input resolution: 96x96x3
Results were kinda similar in both cases.

**Comment by glmanhtu** [comment]
Interesting,
Awesome work, thank you
